import time
import math

from loop_rate_limiters import RateLimiter
import berkeley_humanoid_lite_lowlevel.recoil as recoil
from quadruped_leg_ik import leg_ik

# ============================================================
# Foot position IK test using xbox_home generated homing_offsets.py
# ============================================================
#
# This script is designed to work with homing_offsets.py generated by
# xbox_home_v1/v2, where the recommended IDs avoid CAN ID 0:
#   shank -> ID 3
#   thigh -> ID 2
#   hip   -> ID 1
#
# Required convention from xbox_home:
#   real_joint_angle = raw_motor_position / (MOTOR_SIGN * GEAR_RATIO) + HOMING_OFFSET[id]
#   raw_command = MOTOR_SIGN * (desired_joint_angle - HOMING_OFFSET[id]) * GEAR_RATIO
#
# Key design choices:
#   1. Loads ROLE_TO_ID from homing_offsets.py.
#   2. Refuses to run if any joint is still mapped to CAN ID 0 by default.
#   3. Uses read_position_measured() for startup measured positions.
#   4. Uses transmit_pdo_2() for position commands.
#   5. Does not use write_read_pdo_2() as a fake read.
#   6. Starts by putting all motors into IDLE, then softly arms POSITION mode.
#
# ============================================================

try:
    from homing_offsets import (
        HOMING_OFFSET,
        ROLE_TO_ID,
        GEAR_RATIO as OFFSET_GEAR_RATIO,
        MOTOR_SIGN as OFFSET_MOTOR_SIGN,
    )
except ImportError as exc:
    raise RuntimeError(
        "Could not import homing_offsets.py. Run xbox_home_v2.py first and write offsets."
    ) from exc

try:
    from homing_offsets import RAW_HOMED_POSITION, RAW_READ_SPREAD
except ImportError:
    RAW_HOMED_POSITION = {}
    RAW_READ_SPREAD = {}


# ============================================================
# IDs loaded from xbox_home generated homing_offsets.py
# ============================================================
SHANK_ID = ROLE_TO_ID["shank"]
THIGH_ID = ROLE_TO_ID["thigh"]
HIP_ID = ROLE_TO_ID["hip"]

MOTOR_IDS = [HIP_ID, THIGH_ID, SHANK_ID]
COMMAND_ORDER = [THIGH_ID, SHANK_ID, HIP_ID]  # moving joints first, hip last

MOTOR_NAMES = {
    SHANK_ID: "shank",
    THIGH_ID: "thigh",
    HIP_ID: "hip",
}

ID_TO_ROLE = {v: k for k, v in ROLE_TO_ID.items()}


# ============================================================
# Gear / sign loaded from homing_offsets.py
# ============================================================
GEAR_RATIO = float(OFFSET_GEAR_RATIO)
MOTOR_SIGN = float(OFFSET_MOTOR_SIGN)


# ============================================================
# Safety settings
# ============================================================
REFUSE_CAN_ID_ZERO = True
WARN_IF_CAPTURE_SPREAD_OVER = 0.20

# If the requested move requires more raw radians than this, ask first.
CONFIRM_IF_RAW_DELTA_OVER = 6.0
ABORT_IF_RAW_DELTA_OVER = 25.0


# ============================================================
# Optional adapters for debugging sign / joint assignment
# ============================================================
# Keep these normal first. If a joint moves opposite, flip only that joint.
JOINT_ANGLE_SIGN_BY_ROLE = {
    "hip": 1.0,
    "thigh": 1.0,
    "shank": 1.0,
}

# If later you prove IK thigh/shank are swapped physically, change here only.
IK_ROLE_TO_PHYSICAL_ROLE = {
    "hip": "hip",
    "thigh": "thigh",
    "shank": "shank",
}


# ============================================================
# Default neutral standing pose in IK frame
# ============================================================
NEUTRAL_X = 0.0
NEUTRAL_Y = 84.26
NEUTRAL_Z = 382.0

MOVE_TO_NEUTRAL_ON_START = True
MOVE_TO_NEUTRAL_TIME = 6.0


# ============================================================
# Timing
# ============================================================
RATE_HZ = 80.0
MOVE_TIME = 3.0
PRINT_EVERY = 20


# ============================================================
# Gains
# ============================================================
ARM_KP = 0.0
ARM_KD = 0.0
ARM_TORQUE_LIMIT = 0.0

STARTUP_KP = 0.003
STARTUP_KD = 0.001
STARTUP_TORQUE_LIMIT = 0.03

MID_KP = 0.025
MID_KD = 0.002
MID_TORQUE_LIMIT = 0.12

RUN_KP = 0.055
RUN_KD = 0.003
RUN_TORQUE_LIMIT = 0.25

NEUTRAL_KP = 0.030
NEUTRAL_KD = 0.002

NEUTRAL_TORQUE_LIMIT_BY_ROLE = {
    "thigh": 0.30,
    "shank": 0.30,
    "hip": 0.65,
}


# ============================================================
# Setup
# ============================================================
args = recoil.util.get_args()
bus = recoil.Bus(channel=args.channel, bitrate=1000000)
rate = RateLimiter(frequency=RATE_HZ)

# This tracks the current commanded raw position.
active_cmd = {}


# ============================================================
# Low-level helpers
# ============================================================
def set_mode_with_spacing(motor_id, mode):
    bus.set_mode(motor_id, mode)
    time.sleep(0.008)
    try:
        bus.feed(motor_id)
    except Exception:
        pass
    time.sleep(0.008)


def set_gains(motor_id, kp, kd, torque_limit):
    bus.write_position_kp(motor_id, kp)
    time.sleep(0.004)
    bus.write_position_kd(motor_id, kd)
    time.sleep(0.004)
    bus.write_torque_limit(motor_id, torque_limit)
    time.sleep(0.004)


def set_gains_all(kp, kd, torque_limit):
    for motor_id in MOTOR_IDS:
        set_gains(motor_id, kp, kd, torque_limit)


def set_neutral_gains():
    for motor_id in MOTOR_IDS:
        role = ID_TO_ROLE[motor_id]
        set_gains(
            motor_id,
            NEUTRAL_KP,
            NEUTRAL_KD,
            NEUTRAL_TORQUE_LIMIT_BY_ROLE[role],
        )


def command_position(motor_id, raw_cmd):
    # Command only. Do not use write_read_pdo_2() for reads in this script.
    bus.transmit_pdo_2(motor_id, raw_cmd, 0.0)
    active_cmd[motor_id] = raw_cmd


def command_all_active():
    for motor_id in COMMAND_ORDER:
        command_position(motor_id, active_cmd[motor_id])


def read_measured_position(motor_id):
    value = bus.read_position_measured(motor_id)
    if value is None:
        raise RuntimeError(f"read_position_measured returned None for {MOTOR_NAMES[motor_id]} ID {motor_id}")
    return value


def read_all_measured_positions():
    values = {}
    for motor_id in MOTOR_IDS:
        values[motor_id] = read_measured_position(motor_id)
        time.sleep(0.004)
    return values


def idle_all_motors(stop_bus=True):
    print("\nPutting all motors into IDLE...")
    for motor_id in MOTOR_IDS:
        try:
            set_mode_with_spacing(motor_id, recoil.Mode.IDLE)
            print(f"  {MOTOR_NAMES[motor_id]} ID {motor_id} IDLE")
        except Exception as exc:
            print(f"  Failed to idle {MOTOR_NAMES[motor_id]} ID {motor_id}: {exc}")

    time.sleep(0.15)
    if stop_bus:
        try:
            bus.stop()
        except Exception:
            pass


# ============================================================
# Angle mapping
# ============================================================
def raw_to_real(motor_id, raw_motor_position):
    return raw_motor_position / (MOTOR_SIGN * GEAR_RATIO) + HOMING_OFFSET[motor_id]


def real_to_raw_by_role(physical_role, desired_joint_angle):
    motor_id = ROLE_TO_ID[physical_role]
    sign = JOINT_ANGLE_SIGN_BY_ROLE[physical_role]
    adjusted_angle = sign * desired_joint_angle
    return MOTOR_SIGN * (adjusted_angle - HOMING_OFFSET[motor_id]) * GEAR_RATIO


# ============================================================
# Startup sequence
# ============================================================
def validate_loaded_offsets():
    print("\nValidating loaded homing_offsets.py...")

    for role in ["shank", "thigh", "hip"]:
        if role not in ROLE_TO_ID:
            raise RuntimeError(f"ROLE_TO_ID missing role: {role}")
        motor_id = ROLE_TO_ID[role]
        if motor_id not in HOMING_OFFSET:
            raise RuntimeError(f"HOMING_OFFSET missing ID {motor_id} for role {role}")
        if REFUSE_CAN_ID_ZERO and motor_id == 0:
            raise RuntimeError(
                "CAN ID 0 is still used in homing_offsets.py. "
                "Because ID 0 readback was unstable, reflash away from ID 0 and rerun xbox_home."
            )

    for role in ["shank", "thigh", "hip"]:
        motor_id = ROLE_TO_ID[role]
        spread = RAW_READ_SPREAD.get(motor_id, None)
        if spread is not None and spread > WARN_IF_CAPTURE_SPREAD_OVER:
            print(
                f"  WARNING: {role} ID {motor_id} capture spread {spread:.6f} "
                f"> {WARN_IF_CAPTURE_SPREAD_OVER:.6f}"
            )

    print("  homing_offsets.py looks loadable.")


def read_startup_positions_before_position_mode():
    print("\nPutting all motors into IDLE before startup measured-position read...")
    idle_all_motors(stop_bus=False)

    # Let old frames settle.
    time.sleep(0.35)

    print("\nReading measured startup positions using read_position_measured()...")
    samples_by_id = {motor_id: [] for motor_id in MOTOR_IDS}

    for _ in range(20):
        values = read_all_measured_positions()
        for motor_id in MOTOR_IDS:
            samples_by_id[motor_id].append(values[motor_id])
        rate.sleep()

    startup_raw = {}
    for motor_id in MOTOR_IDS:
        samples = sorted(samples_by_id[motor_id])
        startup_raw[motor_id] = samples[len(samples) // 2]

    print("Startup measured positions:")
    for motor_id in MOTOR_IDS:
        print(
            f"  {MOTOR_NAMES[motor_id]:5s} ID {motor_id}: "
            f"raw={startup_raw[motor_id]:+.6f}, "
            f"real={raw_to_real(motor_id, startup_raw[motor_id]):+.6f}"
        )

    return startup_raw


def arm_position_mode_holding(startup_raw):
    print("\nArming POSITION mode at zero torque while holding measured startup pose...")

    for motor_id in MOTOR_IDS:
        set_gains(motor_id, ARM_KP, ARM_KD, ARM_TORQUE_LIMIT)
        set_mode_with_spacing(motor_id, recoil.Mode.POSITION)

    active_cmd.update(startup_raw)

    # Immediately overwrite firmware target with startup raw position.
    for _ in range(int(0.45 * RATE_HZ)):
        command_all_active()
        rate.sleep()

    print("Ramping to soft startup hold...")
    for step in range(1, 21):
        a = step / 20.0
        for motor_id in MOTOR_IDS:
            set_gains(
                motor_id,
                STARTUP_KP * a,
                STARTUP_KD * a,
                STARTUP_TORQUE_LIMIT * a,
            )
        for _ in range(2):
            command_all_active()
            rate.sleep()

    print("Startup pose is softly held.")


def hold_active_pose(seconds):
    for _ in range(int(seconds * RATE_HZ)):
        command_all_active()
        rate.sleep()


# ============================================================
# IK target construction
# ============================================================
def xyz_to_raw_targets(x, y, z):
    theta_h, theta_t, theta_s = leg_ik(x, y, z)

    desired_by_ik_role = {
        "hip": theta_h,
        "thigh": theta_t,
        "shank": theta_s,
    }

    desired_real_by_id = {}
    raw_targets = {}

    for ik_role, desired_angle in desired_by_ik_role.items():
        physical_role = IK_ROLE_TO_PHYSICAL_ROLE[ik_role]
        motor_id = ROLE_TO_ID[physical_role]
        desired_real_by_id[motor_id] = desired_angle
        raw_targets[motor_id] = real_to_raw_by_role(physical_role, desired_angle)

    return desired_real_by_id, raw_targets


def print_target_summary(x, y, z, desired_real, raw_targets):
    print("\nRequested foot position:")
    print(f"  x = {x:.3f} mm")
    print(f"  y = {y:.3f} mm")
    print(f"  z = {z:.3f} mm")

    print("\nIK angles mapped to physical IDs:")
    for ik_role in ["hip", "thigh", "shank"]:
        physical_role = IK_ROLE_TO_PHYSICAL_ROLE[ik_role]
        motor_id = ROLE_TO_ID[physical_role]
        print(
            f"  IK {ik_role:5s} -> physical {physical_role:5s} "
            f"ID {motor_id}: desired={desired_real[motor_id]:+.6f} rad"
        )

    print("\nRaw motor targets:")
    for motor_id in MOTOR_IDS:
        print(
            f"  {MOTOR_NAMES[motor_id]:5s} "
            f"(ID {motor_id}) = {raw_targets[motor_id]:+.6f}"
        )

    print("\nRaw deltas from active command/current hold:")
    max_delta = 0.0
    for motor_id in MOTOR_IDS:
        current = active_cmd[motor_id]
        delta = raw_targets[motor_id] - current
        max_delta = max(max_delta, abs(delta))
        print(f"  {MOTOR_NAMES[motor_id]:5s} delta = {delta:+.6f} raw rad")

    return max_delta


# ============================================================
# Move helpers
# ============================================================
def maybe_confirm_large_move(max_delta, label):
    if max_delta > ABORT_IF_RAW_DELTA_OVER:
        print(
            f"\nABORTING {label}: max raw delta {max_delta:.3f} > "
            f"ABORT_IF_RAW_DELTA_OVER {ABORT_IF_RAW_DELTA_OVER:.3f}."
        )
        print("This usually means homing offset, joint sign, or joint mapping is wrong.")
        return False

    if max_delta > CONFIRM_IF_RAW_DELTA_OVER:
        print(
            f"\nWARNING: {label} requires max raw delta {max_delta:.3f}, which is large."
        )
        go = input("Move anyway? y/n: ").strip().lower()
        return go in ("y", "yes")

    return True


def move_all_to_targets(raw_targets, move_time):
    start_raw = dict(active_cmd)
    steps = int(move_time * RATE_HZ)

    for i in range(steps):
        u = (i + 1) / steps
        s = 0.5 * (1.0 - math.cos(math.pi * u))

        for motor_id in COMMAND_ORDER:
            cmd = start_raw[motor_id] + (raw_targets[motor_id] - start_raw[motor_id]) * s
            command_position(motor_id, cmd)

        if (i + 1) % PRINT_EVERY == 0:
            try:
                measured = read_all_measured_positions()
                line = []
                for motor_id in COMMAND_ORDER:
                    pos = measured[motor_id]
                    line.append(
                        f"{MOTOR_NAMES[motor_id]} cmd={active_cmd[motor_id]:+.3f} "
                        f"raw={pos:+.3f} real={raw_to_real(motor_id, pos):+.3f}"
                    )
                print(" | ".join(line))
            except Exception as exc:
                print(f"measured-position print warning: {exc}")

        rate.sleep()

    for motor_id in MOTOR_IDS:
        active_cmd[motor_id] = raw_targets[motor_id]


def move_to_neutral_standing():
    print("\nPreparing neutral standing IK pose...")
    desired_real, raw_targets = xyz_to_raw_targets(NEUTRAL_X, NEUTRAL_Y, NEUTRAL_Z)
    max_delta = print_target_summary(NEUTRAL_X, NEUTRAL_Y, NEUTRAL_Z, desired_real, raw_targets)

    if not maybe_confirm_large_move(max_delta, "neutral move"):
        print("Neutral move skipped. Holding current pose instead.")
        return

    print("\nSwitching to neutral move gains...")
    set_neutral_gains()
    hold_active_pose(0.2)

    print("Moving to neutral standing pose...")
    move_all_to_targets(raw_targets, MOVE_TO_NEUTRAL_TIME)
    print("Neutral standing move complete.")


def parse_xyz(text):
    parts = text.replace(",", " ").split()
    if len(parts) != 3:
        raise ValueError("Please enter x y z")
    return float(parts[0]), float(parts[1]), float(parts[2])


# ============================================================
# Main
# ============================================================
try:
    print("=" * 80)
    print("Foot position IK test using xbox_home homing_offsets.py v4")
    print("=" * 80)
    print("This script loads homing_offsets.py generated by xbox_home_v1/v2.")
    print("It uses read_position_measured() for measured reads and transmit_pdo_2() for commands.")
    print("It refuses CAN ID 0 by default because ID 0 readback was unstable.")
    print()
    print("Loaded role -> ID mapping:")
    for role in ["shank", "thigh", "hip"]:
        print(f"  {role:5s} -> ID {ROLE_TO_ID.get(role)}")
    print()
    print("Loaded HOMING_OFFSET:")
    for motor_id in MOTOR_IDS:
        print(f"  {MOTOR_NAMES[motor_id]:5s} (ID {motor_id}) = {HOMING_OFFSET[motor_id]:+.6f}")
    print()
    print("Joint signs:")
    for role in ["hip", "thigh", "shank"]:
        print(f"  {role:5s} sign = {JOINT_ANGLE_SIGN_BY_ROLE[role]:+.1f}")
    print("=" * 80)

    validate_loaded_offsets()

    startup_raw = read_startup_positions_before_position_mode()
    arm_position_mode_holding(startup_raw)

    if MOVE_TO_NEUTRAL_ON_START:
        move_to_neutral_standing()

    print("\nRamping to normal run gains while holding active pose...")
    set_gains_all(MID_KP, MID_KD, MID_TORQUE_LIMIT)
    hold_active_pose(0.3)
    set_gains_all(RUN_KP, RUN_KD, RUN_TORQUE_LIMIT)
    hold_active_pose(0.2)

    print("\nInput x y z in mm.")
    print("Example neutral: 0 84.26 382")
    print("Type q to quit.\n")

    while True:
        text = input("\nEnter x y z (mm): ").strip()
        if text.lower() in ["q", "quit", "exit"]:
            break

        try:
            x, y, z = parse_xyz(text)
            desired_real, raw_targets = xyz_to_raw_targets(x, y, z)
            max_delta = print_target_summary(x, y, z, desired_real, raw_targets)

            if not maybe_confirm_large_move(max_delta, "requested move"):
                continue

            move_all_to_targets(raw_targets, MOVE_TIME)
            print("Move complete.")

        except Exception as exc:
            print(f"Error: {exc}")

except KeyboardInterrupt:
    print("\nInterrupted.")

finally:
    idle_all_motors(stop_bus=True)
